# Add your storage vlass here
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: local-storage
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: jenkins-pv-volume
#  labels:
#    type: local
#spec:
#  storageClassName: linode-block-storage-retain 
#  claimRef:
#    name: jenkins-pv-claim
#    namespace: jenkins
#  capacity:
#    storage: 20Gi
#  accessModes:
#    - ReadWriteOnce
##    path: /mnt
  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  storageClassName: linode-block-storage-retain 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
